<a href="https://colab.research.google.com/github/jahid-fahim/PyTorch_Tutorial/blob/main/A_tipycalNN_InPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Install the Kaggle API client
!pip install kaggle

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory


In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"jahidkarim","key":"5254cb05535e659c0809a77de0fea337"}'}

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "data.csv"

# Load the latest version
df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "pranaykankariya/breastcancer-dataset", file_path,)


/tmp/ipython-input-386996053.py:7: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "pranaykankariya/breastcancer-dataset", file_path,)


Using Colab cache for faster access to the 'breastcancer-dataset' dataset.


In [ ]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
# Drop Columns
df.drop(['id', 'Unnamed: 32'], axis = 1, inplace = True)

In [ ]:
df.shape

(569, 31)

In [ ]:
# Spliting the dataset
from sklearn.model_selection import train_test_split
x = df.drop(['diagnosis'], axis=1)
y = df['diagnosis']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
# Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
y_train

338    B
427    B
406    B
96     B
490    B
      ..
277    M
9      M
359    B
192    B
559    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,

In [ ]:
# Numpy arrays to PyTorch tensors
import torch
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
# Defining the model
class mySimpleNN():
  def __init__(self, x):
    self.weights = torch.rand(x.shape[1], 1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)
# Forward pass
  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

# Loss calculation
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred))
    return loss.mean()


In [ ]:
# Important Parameters
Learning_rate = 0.1
epochs = 25

Training Pipeline

In [ ]:
# Create model
model = mySimpleNN(x_train_tensor)

# Defining Loop
for epoch in range(epochs):
  # Forward pass
  y_pred = model.forward(x_train_tensor)

  # Loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward pass
  loss.backward()

  #Parameters update
  with torch.no_grad():
    model.weights -= Learning_rate * model.weights.grad
    model.bias -= Learning_rate * model.bias.grad

  #Zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.546422668420017
Epoch: 2, Loss: 3.428676611808447
Epoch: 3, Loss: 3.303755546380598
Epoch: 4, Loss: 3.173111254438343
Epoch: 5, Loss: 3.041013670402902
Epoch: 6, Loss: 2.8993339334863113
Epoch: 7, Loss: 2.752112086341804
Epoch: 8, Loss: 2.598004682204331
Epoch: 9, Loss: 2.437566755070651
Epoch: 10, Loss: 2.273560762037036
Epoch: 11, Loss: 2.1136258058525836
Epoch: 12, Loss: 1.9566897720971599
Epoch: 13, Loss: 1.805393162102505
Epoch: 14, Loss: 1.6608959610503842
Epoch: 15, Loss: 1.5253667807785236
Epoch: 16, Loss: 1.3971625201295668
Epoch: 17, Loss: 1.2753993796019933
Epoch: 18, Loss: 1.1693340144521072
Epoch: 19, Loss: 1.079846067668244
Epoch: 20, Loss: 1.0070054103638573
Epoch: 21, Loss: 0.9497984585684262
Epoch: 22, Loss: 0.9061084203311148
Epoch: 23, Loss: 0.8731368428719871
Epoch: 24, Loss: 0.8480649989067637
Epoch: 25, Loss: 0.8285462196975018


In [ ]:
model.weights

tensor([[ 0.3640],
        [-0.0300],
        [ 0.3051],
        [-0.3122],
        [ 0.1154],
        [-0.4178],
        [-0.5199],
        [ 0.1467],
        [ 0.0569],
        [-0.1829],
        [-0.0155],
        [ 0.5190],
        [ 0.3793],
        [ 0.3114],
        [-0.1945],
        [-0.2348],
        [ 0.0172],
        [ 0.4302],
        [ 0.4715],
        [ 0.4403],
        [ 0.0416],
        [ 0.0508],
        [-0.3464],
        [ 0.0272],
        [ 0.4119],
        [ 0.1141],
        [ 0.0231],
        [-0.2750],
        [ 0.1666],
        [-0.1278]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.1392], dtype=torch.float64, requires_grad=True)

Evaluation


In [ ]:
# Model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5246229767799377
