<a href="https://colab.research.google.com/github/jahid-fahim/PyTorch_Tutorial/blob/main/Pytorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install the Kaggle API client
!pip install kaggle

In [2]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory


In [3]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"jahidkarim","key":"5254cb05535e659c0809a77de0fea337"}'}

In [4]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "data.csv"

# Load the latest version
df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "pranaykankariya/breastcancer-dataset", file_path,)


/tmp/ipython-input-386996053.py:7: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(KaggleDatasetAdapter.PANDAS, "pranaykankariya/breastcancer-dataset", file_path,)


100%|██████████| 122k/122k [00:00<00:00, 249kB/s]


In [5]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.shape

(569, 33)

In [7]:
# Drop Columns
df.drop(['id', 'Unnamed: 32'], axis = 1, inplace = True)

In [8]:
df.shape

(569, 31)

In [9]:
# Spliting the dataset
from sklearn.model_selection import train_test_split
x = df.drop(['diagnosis'], axis=1)
y = df['diagnosis']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [10]:
# Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
y_train

338    B
427    B
406    B
96     B
490    B
      ..
277    M
9      M
359    B
192    B
559    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,

In [37]:
# Numpy arrays to PyTorch tensors
import torch
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [38]:
x_train_tensor.shape

torch.Size([455, 30])

In [39]:
import torch.nn as nn

# Defining the model
class mySimpleNN(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features.shape[1], 1)
    self.sigmoid = nn.Sigmoid()

# Forward pass
  def forward(self, x):
    out = self.linear(x)
    out = self.sigmoid(out)

    return out

# Loss calculation
  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # Calculate Loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred))
    return loss.mean()


In [40]:
# Important Parameters
Learning_rate = 0.1
epochs = 25

Training Pipeline

In [42]:
# Create model
model = mySimpleNN(x_train_tensor)

# Defining Loop
for epoch in range(epochs):
  # Forward pass
  y_pred = model(x_train_tensor)

  # Loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)

  # Backward pass
  loss.backward()

  #Parameters update
  with torch.no_grad():
    model.linear.weight -= Learning_rate * model.linear.weight.grad
    model.linear.bias -= Learning_rate * model.linear.bias.grad

  #Zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7425135970115662
Epoch: 2, Loss: 0.7199439406394958
Epoch: 3, Loss: 0.7062699794769287
Epoch: 4, Loss: 0.698032021522522
Epoch: 5, Loss: 0.6929013133049011
Epoch: 6, Loss: 0.6894792318344116
Epoch: 7, Loss: 0.6869884133338928
Epoch: 8, Loss: 0.6850160956382751
Epoch: 9, Loss: 0.6833481192588806
Epoch: 10, Loss: 0.681873619556427
Epoch: 11, Loss: 0.6805346608161926
Epoch: 12, Loss: 0.679298996925354
Epoch: 13, Loss: 0.6781483292579651
Epoch: 14, Loss: 0.6770710349082947
Epoch: 15, Loss: 0.676058828830719
Epoch: 16, Loss: 0.6751055717468262
Epoch: 17, Loss: 0.6742066740989685
Epoch: 18, Loss: 0.6733579039573669
Epoch: 19, Loss: 0.6725554466247559
Epoch: 20, Loss: 0.6717962026596069
Epoch: 21, Loss: 0.6710773706436157
Epoch: 22, Loss: 0.6703962087631226
Epoch: 23, Loss: 0.6697503328323364
Epoch: 24, Loss: 0.6691376566886902
Epoch: 25, Loss: 0.6685558557510376


In [44]:
model.linear.weight

Parameter containing:
tensor([[ 0.0661, -0.0889, -0.0994, -0.0798,  0.0196,  0.0720,  0.0077,  0.0153,
          0.0207,  0.0099,  0.1618,  0.0897, -0.1288, -0.1064, -0.0264, -0.1163,
          0.1097,  0.1038, -0.1420,  0.0644,  0.1494,  0.1069,  0.0101, -0.0051,
         -0.0173, -0.0960, -0.0991, -0.0028,  0.0306, -0.0156]],
       requires_grad=True)

In [45]:
model.linear.bias

Parameter containing:
tensor([-0.3074], requires_grad=True)

Evaluation


In [46]:
# Model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5815635323524475
