<a href="https://colab.research.google.com/github/jahid-fahim/PyTorch_Tutorial/blob/main/Pytorch_nn_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Neural Network with 1 perceptron

In [ ]:
# Create the model
import torch
import torch.nn as nn

class model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




In [ ]:
# Create the dataset
features = torch.rand(10, 5)

# Create the model
model = model(features.shape[1])

# Call model for forward pass
model(features) # model.forward(features)


tensor([[0.6439],
        [0.5771],
        [0.5868],
        [0.6633],
        [0.5867],
        [0.6669],
        [0.6296],
        [0.7275],
        [0.6144],
        [0.6096]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.1941,  0.2798,  0.4442,  0.1253,  0.3152]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.0999], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Now we will buil a complex NN with hidden layer

In [ ]:
# # Create the model
# class MyModel(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()
#     self.linear1 = nn.Linear(num_features, 3)
#     self.relu = nn.ReLU()
#     self.linear2 = nn.Linear(3, 1)
#     self.sigmoid = nn.Sigmoid()

#   def forward(self, features):
#     out = self.linear1(features)
#     out = self.relu(out)
#     out = self.linear2(out)
#     out = self.sigmoid(out)
#     return out

# Can be use sequential container

# Create the model
class MyModel(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [ ]:
# Create the dataset
features = torch.rand(10, 5)

# Create the model (creating object of model class)
model = MyModel(features.shape[1])

# Call model for forward pass
model(features)

tensor([[0.5722],
        [0.5695],
        [0.5551],
        [0.5673],
        [0.5500],
        [0.5498],
        [0.5650],
        [0.5720],
        [0.5610],
        [0.5473]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.1180, -0.3179,  0.2402,  0.2796, -0.2108],
        [-0.3721,  0.2654,  0.0397, -0.3905, -0.0560],
        [ 0.1851,  0.3023, -0.0279, -0.2812, -0.4067]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.0905, -0.3588,  0.3195], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([0.3871], requires_grad=True)

In [ ]:
summary(model, input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00